In [1]:
from model import *
from agents import *
from globals import *
from server import *
from schedule import *
from utility import *

1
watts_strogatz

In [2]:
from mesa.batchrunner import BatchRunner

fixed_params = {"no_of_neighbors": 3,
                "network_type": 2,
                "beta_component": 2,
                "N": 20}

batch_run = BatchRunner(Network,
                        iterations=5,
                        fixed_parameters=fixed_params,
                        max_steps=2,
                        model_reporters={"graph": return_network})
batch_run.run_all()
run_data = batch_run.get_model_vars_dataframe()
print(run_data)

3it [00:00, 25.67it/s]

2
barabasi_albert
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 1}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 7)
{'total_encounters': 3, 'times_agreed': 2}
(0, 8)
{'total_encounters': 3, 'times_agreed': 2}
(0, 11)
{'total_encounters': 3, 'times_agreed': 2}
(0, 12)
{'total_encounters': 3, 'times_agreed': 1}
(0, 14)
{'total_encounters': 3, 'times_agreed': 2}
(0, 18)
{'total_encounters': 3, 'times_agreed': 2}
(0, 19)
{'total_encounters': 3, 'times_agreed': 1}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 7)
{'total_encounters': 3, 'times_agreed': 1}
(1, 10)
{'total_encounters': 3, 'times_agreed': 1}
(1, 13)
{'total_encounters': 3, 'times_agreed': 1}
(1, 14)
{'total_encounters': 3, 'times_agreed': 1}
(1, 17)
{'total_encounters': 3, 'times_agreed': 2}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 4)
{'total_encounters': 3, 'times_agreed': 2}
(3, 5)
{'total_encounters': 3, 'times_agreed': 1}
(3, 8)
{'total_encounters': 3, 'times_agreed': 1}
(3, 9)
{'total_encounters': 3, 'times_agreed': 2}
(3, 10)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 1}
(3, 12)
{'total_encounters': 3, 'times_agreed': 2}
(3, 14)
{'total_encounters': 3, 'times_agreed': 1}
(3, 16)
{'total_encounters': 3, 'times_agreed': 2}
(3, 17)
{'total_encounters': 3, 'times_agreed': 2}
(4, 5)
{'total_encounters': 3, 'times_agreed': 2}
(4, 6)
{'total_encounters': 3, 'times_agreed': 1}
(4, 7)
{'total_encounters': 3, 'times_agreed': 1}
(4, 8)
{'total_encounters': 3, 'times_agreed': 1}
(4, 9)
{'total_encounters': 3, 'times_agreed': 1}
(4, 11)
{'total_encounters': 3, 'times_agreed': 1}
(4, 12)
{'total_encounters': 3, 'times_agreed': 1}
(4, 16)
{'total_encounters': 3, 'times_agreed': 2}
(4, 17)
{'total_encounters': 3, 'times_agreed': 1}
(4, 18)
{'total_encounters': 3, 'times_agreed': 1}
(4, 19)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 16)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 1}
(8, 13)
{'total_encounters': 3, 'times_agreed': 2}
(8, 19)
{'total_encounters': 3, 'times_agreed': 1}
(9, 10)
{'total_encounters': 3, 'times_agreed': 1}
(10, 15)
{'total_encounters': 3, 'times_agreed': 1}
(10, 18)
{'total_encounters': 3, 'times_agreed': 2}
(12, 15)
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 1}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 7)
{'total_encounters': 3, 'times_agreed': 2}
(0, 8)
{'total_encounters': 3, 'times_agreed': 2}
(0, 11)
{'total_encounters': 3, 'times_agreed': 2}
(0, 12)
{'total_encounters': 3, 'times_agreed': 1}
(0, 14)
{'total_encounters': 3, 'times_agreed': 2}
(0, 18)
{'total_encounters': 3, 'times_agreed': 2}
(0, 19)
{'total_encounters': 3, 'times_agreed': 1}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 7)
{'total_encounters': 3, 'times_agreed': 1}
(1, 10)
{'total_encounters': 3, 'times_agreed': 1}
(1, 13)
{'total_encounters': 3, 'times_agreed': 1}
(1, 14)
{'total_encounters': 3, 'times_agreed': 1}
(1, 17)
{'total_encounters': 3, 'times_agreed': 2}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 4)
{'total_encounters': 3, 'times_agreed': 2}
(3, 5)
{'total_encounters': 3, 'times_agreed': 1}
(3, 8)
{'total_encounters': 3, 'times_agreed': 1}
(3, 9)
{'total_encounters': 3, 'times_agreed': 2}
(3, 10)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 1}
(3, 12)
{'total_encounters': 3, 'times_agreed': 2}
(3, 14)
{'total_encounters': 3, 'times_agreed': 1}
(3, 16)
{'total_encounters': 3, 'times_agreed': 2}
(3, 17)
{'total_encounters': 3, 'times_agreed': 2}
(4, 5)
{'total_encounters': 3, 'times_agreed': 2}
(4, 6)
{'total_encounters': 3, 'times_agreed': 1}
(4, 7)
{'total_encounters': 3, 'times_agreed': 1}
(4, 8)
{'total_encounters': 3, 'times_agreed': 1}
(4, 9)
{'total_encounters': 3, 'times_agreed': 1}
(4, 11)
{'total_encounters': 3, 'times_agreed': 1}
(4, 12)
{'total_encounters': 3, 'times_agreed': 1}
(4, 16)
{'total_encounters': 3, 'times_agreed': 2}
(4, 17)
{'total_encounters': 3, 'times_agreed': 1}
(4, 18)
{'total_encounters': 3, 'times_agreed': 1}
(4, 19)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 16)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 1}
(8, 13)
{'total_encounters': 3, 'times_agreed': 2}
(8, 19)
{'total_encounters': 3, 'times_agreed': 1}
(9, 10)
{'total_encounters': 3, 'times_agreed': 1}
(10, 15)
{'total_encounters': 3, 'times_agreed': 1}
(10, 18)
{'total_encounters': 3, 'times_agreed': 2}
(12, 15)
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 1}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 7)
{'total_encounters': 3, 'times_agreed': 2}
(0, 8)
{'total_encounters': 3, 'times_agreed': 2}
(0, 11)
{'total_encounters': 3, 'times_agreed': 2}
(0, 12)
{'total_encounters': 3, 'times_agreed': 1}
(0, 14)
{'total_encounters': 3, 'times_agreed': 2}
(0, 18)
{'total_encounters': 3, 'times_agreed': 2}
(0, 19)
{'total_encounters': 3, 'times_agreed': 1}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 7)
{'total_encounters': 3, 'times_agreed': 1}
(1, 10)
{'total_encounters': 3, 'times_agreed': 1}
(1, 13)
{'total_encounters': 3, 'times_agreed': 1}
(1, 14)
{'total_encounters': 3, 'times_agreed': 1}
(1, 17)
{'total_encounters': 3, 'times_agreed': 2}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 4)
{'total_encounters': 3, 'times_agreed': 2}
(3, 5)
{'total_encounters': 3, 'times_agreed': 1}
(3, 8)
{'total_encounters': 3, 'times_agreed': 1}
(3, 9)
{'total_encounters': 3, 'times_agreed': 2}
(3, 10)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 1}
(3, 12)
{'total_encounters': 3, 'times_agreed': 2}
(3, 14)
{'total_encounters': 3, 'times_agreed': 1}
(3, 16)
{'total_encounters': 3, 'times_agreed': 2}
(3, 17)
{'total_encounters': 3, 'times_agreed': 2}
(4, 5)
{'total_encounters': 3, 'times_agreed': 2}
(4, 6)
{'total_encounters': 3, 'times_agreed': 1}
(4, 7)
{'total_encounters': 3, 'times_agreed': 1}
(4, 8)
{'total_encounters': 3, 'times_agreed': 1}
(4, 9)
{'total_encounters': 3, 'times_agreed': 1}
(4, 11)
{'total_encounters': 3, 'times_agreed': 1}
(4, 12)
{'total_encounters': 3, 'times_agreed': 1}
(4, 16)
{'total_encounters': 3, 'times_agreed': 2}
(4, 17)
{'total_encounters': 3, 'times_agreed': 1}
(4, 18)
{'total_encounters': 3, 'times_agreed': 1}
(4, 19)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 16)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 1}
(8, 13)
{'total_encounters': 3, 'times_agreed': 2}
(8, 19)
{'total_encounters': 3, 'times_agreed': 1}
(9, 10)
{'total_encounters': 3, 'times_agreed': 1}
(10, 15)
{'total_encounters': 3, 'times_agreed': 1}
(10, 18)
{'total_encounters': 3, 'times_agreed': 2}
(12, 15)
2
barabasi_albert
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 1}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 1}
(0, 7)
{'total_encounters': 3, 'times_agreed': 1}
(0, 8)
{'total_encounters': 3, 'times_agreed': 2}
(0, 11)
{'total_encounters': 3, 'times_agreed': 2}
(0, 14)
{'total_encounters': 3, 'times_agreed': 1}
(0, 15)
{'total_encounters': 3, 'times_agreed': 1}
(0, 17)
{'total_encounters': 3, 'times_agreed': 2}
(0, 18)
{'total_encounters': 3, 'times_agreed': 2}
(1, 3)
{'total_encounters': 3, 'times_agreed': 2}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 8)
{'total_encounters': 3, 'times_agreed': 2}
(1, 9)
{'total_encounters': 3, 'times_agreed': 2}
(1, 10)
{'total_encounters': 3, 'times_agreed': 2}
(1, 12)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 1}
(2, 5)
{'total_encounters': 3, 'times_agreed': 1}
(2, 7)
{'total_encounters': 3, 'times_agreed': 1}
(2, 12)
{'total_encounters': 3, 'times_agreed': 2}
(2, 18)
{'total_encounters': 3, 'times_agreed': 2}
(3, 4)
{'total_encounters': 3, 'times_agreed': 2}
(3, 9)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 2}
(4, 5)
{'total_encounters': 3, 'times_agreed': 1}
(4, 6)
{'total_encounters': 3, 'times_agreed': 2}
(4, 7)
{'total_encounters': 3, 'times_agreed': 2}
(4, 9)
{'total_encounters': 3, 'times_agreed': 2}
(4, 10)
{'total_encounters': 3, 'times_agreed': 1}
(5, 13)
{'total_encounters': 3, 'times_agreed': 1}
(5, 16)
{'total_encounters': 3, 'times_agreed': 2}
(5, 17)
{'total_encounters': 3, 'times_agreed': 1}
(6, 10)
{'total_encounters': 3, 'times_agreed': 2}
(6, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 8)
{'total_encounters': 3, 'times_agreed': 2}
(7, 12)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 1}
(7, 16)
{'total_encounters': 3, 'times_agreed': 2}
(7, 19)
{'total_encounters': 3, 'times_agreed': 1}
(8, 11)
{'total_encounters': 3, 'times_agreed': 1}
(8, 14)
{'total_encounters': 3, 'times_agreed': 2}
(8, 19)
{'total_encounters': 3, 'times_agreed': 2}
(10, 15)
{'total_encounters': 3, 'times_agreed': 2}
(11, 13)
{'total_encounters': 3, 'times_agreed': 1}
(12, 16)
{'total_encounters': 3, 'times_agreed': 1}
(12, 18)
{'total_encounters': 3, 'times_agreed': 1}
(13, 17)
{'total_encounters': 3, 'times_agreed': 1}
(13, 19)
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 1}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 1}
(0, 7)
{'total_encounters': 3, 'times_agreed': 1}
(0, 8)
{'total_encounters': 3, 'times_agreed': 2}
(0, 11)
{'total_encounters': 3, 'times_agreed': 2}
(0, 14)
{'total_encounters': 3, 'times_agreed': 1}
(0, 15)
{'total_encounters': 3, 'times_agreed': 1}
(0, 17)
{'total_encounters': 3, 'times_agreed': 2}
(0, 18)
{'total_encounters': 3, 'times_agreed': 2}
(1, 3)
{'total_encounters': 3, 'times_agreed': 2}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 8)
{'total_encounters': 3, 'times_agreed': 2}
(1, 9)
{'total_encounters': 3, 'times_agreed': 2}
(1, 10)
{'total_encounters': 3, 'times_agreed': 2}
(1, 12)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 1}
(2, 5)
{'total_encounters': 3, 'times_agreed': 1}
(2, 7)
{'total_encounters': 3, 'times_agreed': 1}
(2, 12)
{'total_encounters': 3, 'times_agreed': 2}
(2, 18)
{'total_encounters': 3, 'times_agreed': 2}
(3, 4)
{'total_encounters': 3, 'times_agreed': 2}
(3, 9)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 2}
(4, 5)
{'total_encounters': 3, 'times_agreed': 1}
(4, 6)
{'total_encounters': 3, 'times_agreed': 2}
(4, 7)
{'total_encounters': 3, 'times_agreed': 2}
(4, 9)
{'total_encounters': 3, 'times_agreed': 2}
(4, 10)
{'total_encounters': 3, 'times_agreed': 1}
(5, 13)
{'total_encounters': 3, 'times_agreed': 1}
(5, 16)
{'total_encounters': 3, 'times_agreed': 2}
(5, 17)
{'total_encounters': 3, 'times_agreed': 1}
(6, 10)
{'total_encounters': 3, 'times_agreed': 2}
(6, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 8)
{'total_encounters': 3, 'times_agreed': 2}
(7, 12)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 1}
(7, 16)
{'total_encounters': 3, 'times_agreed': 2}
(7, 19)
{'total_encounters': 3, 'times_agreed': 1}
(8, 11)
{'total_encounters': 3, 'times_agreed': 1}
(8, 14)
{'total_encounters': 3, 'times_agreed': 2}
(8, 19)
{'total_encounters': 3, 'times_agreed': 2}
(10, 15)
{'total_encounters': 3, 'times_agreed': 2}
(11, 13)
{'total_encounters': 3, 'times_agreed': 1}
(12, 16)
{'total_encounters': 3, 'times_agreed': 1}
(12, 18)
{'total_encounters': 3, 'times_agreed': 1}
(13, 17)
{'total_encounters': 3, 'times_agreed': 1}
(13, 19)
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 1}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 1}
(0, 7)
{'total_encounters': 3, 'times_agreed': 1}
(0, 8)
{'total_encounters': 3, 'times_agreed': 2}
(0, 11)
{'total_encounters': 3, 'times_agreed': 2}
(0, 14)
{'total_encounters': 3, 'times_agreed': 1}
(0, 15)
{'total_encounters': 3, 'times_agreed': 1}
(0, 17)
{'total_encounters': 3, 'times_agreed': 2}
(0, 18)
{'total_encounters': 3, 'times_agreed': 2}
(1, 3)
{'total_encounters': 3, 'times_agreed': 2}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 8)
{'total_encounters': 3, 'times_agreed': 2}
(1, 9)
{'total_encounters': 3, 'times_agreed': 2}
(1, 10)
{'total_encounters': 3, 'times_agreed': 2}
(1, 12)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 1}
(2, 5)
{'total_encounters': 3, 'times_agreed': 1}
(2, 7)
{'total_encounters': 3, 'times_agreed': 1}
(2, 12)
{'total_encounters': 3, 'times_agreed': 2}
(2, 18)
{'total_encounters': 3, 'times_agreed': 2}
(3, 4)
{'total_encounters': 3, 'times_agreed': 2}
(3, 9)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 2}
(4, 5)
{'total_encounters': 3, 'times_agreed': 1}
(4, 6)
{'total_encounters': 3, 'times_agreed': 2}
(4, 7)
{'total_encounters': 3, 'times_agreed': 2}
(4, 9)
{'total_encounters': 3, 'times_agreed': 2}
(4, 10)
{'total_encounters': 3, 'times_agreed': 1}
(5, 13)
{'total_encounters': 3, 'times_agreed': 1}
(5, 16)
{'total_encounters': 3, 'times_agreed': 2}
(5, 17)
{'total_encounters': 3, 'times_agreed': 1}
(6, 10)
{'total_encounters': 3, 'times_agreed': 2}
(6, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 8)
{'total_encounters': 3, 'times_agreed': 2}
(7, 12)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 1}
(7, 16)
{'total_encounters': 3, 'times_agreed': 2}
(7, 19)
{'total_encounters': 3, 'times_agreed': 1}
(8, 11)
{'total_encounters': 3, 'times_agreed': 1}
(8, 14)
{'total_encounters': 3, 'times_agreed': 2}
(8, 19)
{'total_encounters': 3, 'times_agreed': 2}
(10, 15)
{'total_encounters': 3, 'times_agreed': 2}
(11, 13)
{'total_encounters': 3, 'times_agreed': 1}
(12, 16)
{'total_encounters': 3, 'times_agreed': 1}
(12, 18)
{'total_encounters': 3, 'times_agreed': 1}
(13, 17)
{'total_encounters': 3, 'times_agreed': 1}
(13, 19)
2
barabasi_albert
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 2}
(0, 4)
{'total_encounters': 3, 'times_agreed': 2}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 2}
(0, 8)
{'total_encounters': 3, 'times_agreed': 1}
(0, 9)
{'total_encounters': 3, 'times_agreed': 2}
(0, 12)
{'total_encounters': 3, 'times_agreed': 1}
(0, 13)
{'total_encounters': 3, 'times_agreed': 1}
(0, 14)
{'total_encounters': 3, 'times_agreed': 2}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 7)
{'total_encounters': 3, 'times_agreed': 1}
(1, 10)
{'total_encounters': 3, 'times_agreed': 1}
(1, 12)
{'total_encounters': 3, 'times_agreed': 2}
(1, 14)
{'total_encounters': 3, 'times_agreed': 2}
(1, 15)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 5)
{'total_encounters': 3, 'times_agreed': 2}
(2, 8)
{'total_encounters': 3, 'times_agreed': 1}
(2, 14)
{'total_encounters': 3, 'times_agreed': 1}
(3, 4)
{'total_encounters': 3, 'times_agreed': 1}
(3, 5)
{'total_encounters': 3, 'times_agreed': 1}
(3, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 7)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 1}
(3, 12)
{'total_encounters': 3, 'times_agreed': 2}
(3, 13)
{'total_encounters': 3, 'times_agreed': 1}
(3, 16)
{'total_encounters': 3, 'times_agreed': 1}
(5, 7)
{'total_encounters': 3, 'times_agreed': 2}
(5, 8)
{'total_encounters': 3, 'times_agreed': 1}
(5, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 2}
(6, 10)
{'total_encounters': 3, 'times_agreed': 1}
(7, 10)
{'total_encounters': 3, 'times_agreed': 2}
(7, 13)
{'total_encounters': 3, 'times_agreed': 2}
(7, 19)
{'total_encounters': 3, 'times_agreed': 2}
(8, 11)
{'total_encounters': 3, 'times_agreed': 2}
(8, 17)
{'total_encounters': 3, 'times_agreed': 1}
(9, 11)
{'total_encounters': 3, 'times_agreed': 2}
(9, 15)
{'total_encounters': 3, 'times_agreed': 1}
(9, 16)
{'total_encounters': 3, 'times_agreed': 2}
(9, 19)
{'total_encounters': 3, 'times_agreed': 2}
(10, 18)
{'total_encounters': 3, 'times_agreed': 2}
(11, 17)
{'total_encounters': 3, 'times_agreed': 1}
(13, 16)
{'total_encounters': 3, 'times_agreed': 1}
(13, 17)
{'total_encounters': 3, 'times_agreed': 1}
(13, 18)
{'total_encounters': 3, 'times_agreed': 2}
(14, 15)
{'total_encounters': 3, 'times_agreed': 1}
(15, 18)
{'total_encounters': 3, 'times_agreed': 2}
(15, 19)
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 2}
(0, 4)
{'total_encounters': 3, 'times_agreed': 2}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 2}
(0, 8)
{'total_encounters': 3, 'times_agreed': 1}
(0, 9)
{'total_encounters': 3, 'times_agreed': 2}
(0, 12)
{'total_encounters': 3, 'times_agreed': 1}
(0, 13)
{'total_encounters': 3, 'times_agreed': 1}
(0, 14)
{'total_encounters': 3, 'times_agreed': 2}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 4)
{'total_encounters': 3, 'times_agreed': 1}
(1, 6)
{'total_encounters': 3, 'times_agreed': 2}
(1, 7)
{'total_encounters': 3, 'times_agreed': 1}
(1, 10)
{'total_encounters': 3, 'times_agreed': 1}
(1, 12)
{'total_encounters': 3, 'times_agreed': 2}
(1, 14)
{'total_encounters': 3, 'times_agreed': 2}
(1, 15)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 5)
{'total_encounters': 3, 'times_agreed': 2}
(2, 8)
{'total_encounters': 3, 'times_agreed': 1}
(2, 14)
{'total_encounters': 3, 'times_agreed': 1}
(3, 4)
{'total_encounters': 3, 'times_agreed': 1}
(3, 5)
{'total_encounters': 3, 'times_agreed': 1}
(3, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 7)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 1}
(3, 12)
{'total_encounters': 3, 'times_agreed': 2}
(3, 13)
{'total_encounters': 3, 'times_agreed': 1}
(3, 16)
{'total_encounters': 3, 'times_agreed': 1}
(5, 7)
{'total_encounters': 3, 'times_agreed': 2}
(5, 8)
{'total_encounters': 3, 'times_agreed': 1}
(5, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 2}
(6, 10)
{'total_encounters': 3, 'times_agreed': 1}
(7, 10)
{'total_encounters': 3, 'times_agreed': 2}
(7, 13)

{'total_encounters': 3, 'times_agreed': 2}
(4, 14)
{'total_encounters': 3, 'times_agreed': 2}
(4, 15)
{'total_encounters': 3, 'times_agreed': 2}
(4, 17)
{'total_encounters': 3, 'times_agreed': 2}
(4, 18)
{'total_encounters': 3, 'times_agreed': 2}
(5, 8)
{'total_encounters': 3, 'times_agreed': 2}
(5, 18)
{'total_encounters': 3, 'times_agreed': 1}
(7, 9)
{'total_encounters': 3, 'times_agreed': 2}
(7, 10)
{'total_encounters': 3, 'times_agreed': 1}
(7, 12)
{'total_encounters': 3, 'times_agreed': 2}
(7, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 2}
(8, 13)
{'total_encounters': 3, 'times_agreed': 1}
(8, 19)
{'total_encounters': 3, 'times_agreed': 1}
(9, 16)
{'total_encounters': 3, 'times_agreed': 2}
(9, 19)
{'total_encounters': 3, 'times_agreed': 2}
(11, 18)
{'total_encounters': 3, 'times_agreed': 1}
(12, 13)
{'total_encounters': 3, 'times_agreed': 2}
(13, 14)
{'total_encounters': 3, 'times_agreed': 2}
(13, 15)
{'total_encounters': 3, 'times_agreed': 1}
(14, 19)
{'total_encounters': 3, 'times_agreed': 2}
(0, 3)
{'total_encounters': 3, 'times_agreed': 1}
(0, 4)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 1}
(0, 7)
{'total_encounters': 3, 'times_agreed': 2}
(0, 9)
{'total_encounters': 3, 'times_agreed': 1}
(0, 11)
{'total_encounters': 3, 'times_agreed': 2}
(0, 12)
{'total_encounters': 3, 'times_agreed': 1}
(0, 16)
{'total_encounters': 3, 'times_agreed': 2}
(1, 3)
{'total_encounters': 3, 'times_agreed': 2}
(1, 6)
{'total_encounters': 3, 'times_agreed': 1}
(1, 10)
{'total_encounters': 3, 'times_agreed': 2}
(2, 3)
{'total_encounters': 3, 'times_agreed': 1}
(2, 4)
{'total_encounters': 3, 'times_agreed': 1}
(2, 5)
{'total_encounters': 3, 'times_agreed': 1}
(2, 7)
{'total_encounters': 3, 'times_agreed': 1}
(2, 8)
{'total_encounters': 3, 'times_agreed': 2}
(2, 9)
{'total_encounters': 3, 'times_agreed': 1}
(2, 11)
{'total_encounters': 3, 'times_agreed': 1}
(2, 13)
{'total_encounters': 3, 'times_agreed': 1}
(2, 16)
{'total_encounters': 3, 'times_agreed': 1}
(2, 17)
{'total_encounters': 3, 'times_agreed': 1}
(3, 4)
{'total_encounters': 3, 'times_agreed': 1}
(3, 5)
{'total_encounters': 3, 'times_agreed': 1}
(3, 7)
{'total_encounters': 3, 'times_agreed': 1}
(3, 11)
{'total_encounters': 3, 'times_agreed': 1}
(3, 17)
{'total_encounters': 3, 'times_agreed': 2}
(4, 5)
{'total_encounters': 3, 'times_agreed': 1}
(4, 6)
{'total_encounters': 3, 'times_agreed': 2}
(4, 8)
{'total_encounters': 3, 'times_agreed': 2}
(4, 10)
{'total_encounters': 3, 'times_agreed': 1}
(4, 12)
{'total_encounters': 3, 'times_agreed': 2}
(4, 14)
{'total_encounters': 3, 'times_agreed': 2}
(4, 15)
{'total_encounters': 3, 'times_agreed': 2}
(4, 17)
{'total_encounters': 3, 'times_agreed': 2}
(4, 18)
{'total_encounters': 3, 'times_agreed': 2}
(5, 8)
{'total_encounters': 3, 'times_agreed': 2}
(5, 18)
{'total_encounters': 3, 'times_agreed': 1}
(7, 9)
{'total_encounters': 3, 'times_agreed': 2}
(7, 10)
{'total_encounters': 3, 'times_agreed': 1}
(7, 12)
{'total_encounters': 3, 'times_agreed': 2}
(7, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 15)
{'total_encounters': 3, 'times_agreed': 2}
(8, 13)
{'total_encounters': 3, 'times_agreed': 1}
(8, 19)
{'total_encounters': 3, 'times_agreed': 1}
(9, 16)
{'total_encounters': 3, 'times_agreed': 2}
(9, 19)
{'total_encounters': 3, 'times_agreed': 2}
(11, 18)
{'total_encounters': 3, 'times_agreed': 1}
(12, 13)
{'total_encounters': 3, 'times_agreed': 2}
(13, 14)
{'total_encounters': 3, 'times_agreed': 2}
(13, 15)
{'total_encounters': 3, 'times_agreed': 1}
(14, 19)
2
barabasi_albert
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 2}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 2}
(0, 16)
{'total_encounters': 3, 'times_agreed': 1}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 7)
{'total_encounters': 3, 'times_agreed': 2}
(1, 11)
{'total_encounters': 3, 'times_agreed': 2}
(1, 15)
{'total_encounters': 3, 'times_agreed': 1}
(1, 17)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 4)
{'total_encounters': 3, 'times_agreed': 1}
(2, 5)
{'total_encounters': 3, 'times_agreed': 1}
(2, 7)
{'total_encounters': 3, 'times_agreed': 1}
(2, 10)
{'total_encounters': 3, 'times_agreed': 2}
(2, 11)
{'total_encounters': 3, 'times_agreed': 2}
(2, 13)
{'total_encounters': 3, 'times_agreed': 2}
(2, 16)
{'total_encounters': 3, 'times_agreed': 2}
(2, 18)
{'total_encounters': 3, 'times_agreed': 1}
(2, 19)
{'total_encounters': 3, 'times_agreed': 1}
(3, 4)
{'total_encounters': 3, 'times_agreed': 1}
(3, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 8)
{'total_encounters': 3, 'times_agreed': 2}
(3, 9)
{'total_encounters': 3, 'times_agreed': 1}
(3, 15)
{'total_encounters': 3, 'times_agreed': 1}
(4, 5)
{'total_encounters': 3, 'times_agreed': 2}
(4, 6)
{'total_encounters': 3, 'times_agreed': 1}
(4, 9)
{'total_encounters': 3, 'times_agreed': 2}
(4, 11)
{'total_encounters': 3, 'times_agreed': 2}
(4, 14)
{'total_encounters': 3, 'times_agreed': 2}
(5, 8)
{'total_encounters': 3, 'times_agreed': 2}
(5, 10)
{'total_encounters': 3, 'times_agreed': 1}
(6, 7)
{'total_encounters': 3, 'times_agreed': 1}
(6, 8)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 10)
{'total_encounters': 3, 'times_agreed': 1}
(6, 12)
{'total_encounters': 3, 'times_agreed': 2}
(6, 13)
{'total_encounters': 3, 'times_agreed': 1}
(6, 17)
{'total_encounters': 3, 'times_agreed': 2}
(7, 12)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 1}
(7, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 19)
{'total_encounters': 3, 'times_agreed': 2}
(8, 17)
{'total_encounters': 3, 'times_agreed': 2}
(10, 12)
{'total_encounters': 3, 'times_agreed': 1}
(10, 15)
{'total_encounters': 3, 'times_agreed': 1}
(10, 16)
{'total_encounters': 3, 'times_agreed': 1}
(12, 18)
{'total_encounters': 3, 'times_agreed': 2}
(13, 14)
{'total_encounters': 3, 'times_agreed': 2}
(16, 18)
{'total_encounters': 3, 'times_agreed': 1}
(18, 19)
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 2}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 2}
(0, 16)
{'total_encounters': 3, 'times_agreed': 1}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 7)
{'total_encounters': 3, 'times_agreed': 2}
(1, 11)
{'total_encounters': 3, 'times_agreed': 2}
(1, 15)
{'total_encounters': 3, 'times_agreed': 1}
(1, 17)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 4)
{'total_encounters': 3, 'times_agreed': 1}
(2, 5)
{'total_encounters': 3, 'times_agreed': 1}
(2, 7)
{'total_encounters': 3, 'times_agreed': 1}
(2, 10)
{'total_encounters': 3, 'times_agreed': 2}
(2, 11)
{'total_encounters': 3, 'times_agreed': 2}
(2, 13)
{'total_encounters': 3, 'times_agreed': 2}
(2, 16)
{'total_encounters': 3, 'times_agreed': 2}
(2, 18)
{'total_encounters': 3, 'times_agreed': 1}
(2, 19)
{'total_encounters': 3, 'times_agreed': 1}
(3, 4)
{'total_encounters': 3, 'times_agreed': 1}
(3, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 8)
{'total_encounters': 3, 'times_agreed': 2}
(3, 9)
{'total_encounters': 3, 'times_agreed': 1}
(3, 15)
{'total_encounters': 3, 'times_agreed': 1}
(4, 5)
{'total_encounters': 3, 'times_agreed': 2}
(4, 6)
{'total_encounters': 3, 'times_agreed': 1}
(4, 9)
{'total_encounters': 3, 'times_agreed': 2}
(4, 11)
{'total_encounters': 3, 'times_agreed': 2}
(4, 14)
{'total_encounters': 3, 'times_agreed': 2}
(5, 8)
{'total_encounters': 3, 'times_agreed': 2}
(5, 10)
{'total_encounters': 3, 'times_agreed': 1}
(6, 7)
{'total_encounters': 3, 'times_agreed': 1}
(6, 8)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 10)
{'total_encounters': 3, 'times_agreed': 1}
(6, 12)
{'total_encounters': 3, 'times_agreed': 2}
(6, 13)
{'total_encounters': 3, 'times_agreed': 1}
(6, 17)
{'total_encounters': 3, 'times_agreed': 2}
(7, 12)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 1}
(7, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 19)
{'total_encounters': 3, 'times_agreed': 2}
(8, 17)
{'total_encounters': 3, 'times_agreed': 2}
(10, 12)
{'total_encounters': 3, 'times_agreed': 1}
(10, 15)
{'total_encounters': 3, 'times_agreed': 1}
(10, 16)
{'total_encounters': 3, 'times_agreed': 1}
(12, 18)
{'total_encounters': 3, 'times_agreed': 2}
(13, 14)
{'total_encounters': 3, 'times_agreed': 2}
(16, 18)
{'total_encounters': 3, 'times_agreed': 1}
(18, 19)
{'total_encounters': 3, 'times_agreed': 1}
(0, 3)
{'total_encounters': 3, 'times_agreed': 2}
(0, 4)
{'total_encounters': 3, 'times_agreed': 1}
(0, 5)
{'total_encounters': 3, 'times_agreed': 2}
(0, 6)
{'total_encounters': 3, 'times_agreed': 2}
(0, 16)
{'total_encounters': 3, 'times_agreed': 1}
(1, 3)
{'total_encounters': 3, 'times_agreed': 1}
(1, 7)
{'total_encounters': 3, 'times_agreed': 2}
(1, 11)
{'total_encounters': 3, 'times_agreed': 2}
(1, 15)
{'total_encounters': 3, 'times_agreed': 1}
(1, 17)
{'total_encounters': 3, 'times_agreed': 1}
(2, 3)
{'total_encounters': 3, 'times_agreed': 2}
(2, 4)
{'total_encounters': 3, 'times_agreed': 1}
(2, 5)
{'total_encounters': 3, 'times_agreed': 1}
(2, 7)
{'total_encounters': 3, 'times_agreed': 1}
(2, 10)
{'total_encounters': 3, 'times_agreed': 2}
(2, 11)
{'total_encounters': 3, 'times_agreed': 2}
(2, 13)
{'total_encounters': 3, 'times_agreed': 2}
(2, 16)
{'total_encounters': 3, 'times_agreed': 2}
(2, 18)
{'total_encounters': 3, 'times_agreed': 1}
(2, 19)
{'total_encounters': 3, 'times_agreed': 1}
(3, 4)
{'total_encounters': 3, 'times_agreed': 1}
(3, 6)
{'total_encounters': 3, 'times_agreed': 2}
(3, 8)
{'total_encounters': 3, 'times_agreed': 2}
(3, 9)

5it [00:00, 24.67it/s]

{'total_encounters': 3, 'times_agreed': 1}
(3, 15)
{'total_encounters': 3, 'times_agreed': 1}
(4, 5)
{'total_encounters': 3, 'times_agreed': 2}
(4, 6)
{'total_encounters': 3, 'times_agreed': 1}
(4, 9)
{'total_encounters': 3, 'times_agreed': 2}
(4, 11)
{'total_encounters': 3, 'times_agreed': 2}
(4, 14)
{'total_encounters': 3, 'times_agreed': 2}
(5, 8)
{'total_encounters': 3, 'times_agreed': 2}
(5, 10)
{'total_encounters': 3, 'times_agreed': 1}
(6, 7)
{'total_encounters': 3, 'times_agreed': 1}
(6, 8)
{'total_encounters': 3, 'times_agreed': 1}
(6, 9)
{'total_encounters': 3, 'times_agreed': 1}
(6, 10)
{'total_encounters': 3, 'times_agreed': 1}
(6, 12)
{'total_encounters': 3, 'times_agreed': 2}
(6, 13)
{'total_encounters': 3, 'times_agreed': 1}
(6, 17)
{'total_encounters': 3, 'times_agreed': 2}
(7, 12)
{'total_encounters': 3, 'times_agreed': 1}
(7, 13)
{'total_encounters': 3, 'times_agreed': 1}
(7, 14)
{'total_encounters': 3, 'times_agreed': 2}
(7, 19)
{'total_encounters': 3, 'times_agreed': 2}
(8, 17)
{'total_encounters': 3, 'times_agreed': 2}
(10, 12)
{'total_encounters': 3, 'times_agreed': 1}
(10, 15)
{'total_encounters': 3, 'times_agreed': 1}
(10, 16)
{'total_encounters': 3, 'times_agreed': 1}
(12, 18)
{'total_encounters': 3, 'times_agreed': 2}
(13, 14)
{'total_encounters': 3, 'times_agreed': 2}
(16, 18)
{'total_encounters': 3, 'times_agreed': 1}
(18, 19)
   Run graph  no_of_neighbors  network_type  beta_component   N
0    0  None                3             2               2  20
1    1  None                3             2               2  20
2    2  None                3             2               2  20
3    3  None                3             2               2  20
4    4  None                3             2               2  20